import React from 'react';
import { Grid } from 'react-bootstrap';

function Disclaimer () {
  return(
    <Grid>
      <p>
        THIS WEBSITE IS OWNED AND OPERATED BY AN MDC/HEMPWORX INDEPENDENT AFFILIATE AND IS NOT ENDORSED BY MYDAILYCHOICE INC. ANY OPINIONS EXPRESSED ON THIS WEBSITE ARE MADE BY AND THE RESPONSIBILITY OF THE INDIVIDUAL AFFILIATE AND SHOULD NOT BE CONSTRUCTED AS A REPRESENTATION OF THE OPINIONS OF MYDAILYCHOICE.INC, STATEMENTS MADE ON THE PRODUCTS, WEBSITE, OR SALES MATERIALS HAVE NOT BEEN EVALUATED BY THE FOOD AND DRUG ADMINISTRATION. MYDAILYCHOICE.INC. PRODUCTS ARE NOT INTENDED TO DIAGNOSE, TREAT, CURE, OR PREVENT AND DISEASE, MYDAILYCHOICE,INC, PRODUCTS ARE NOT INTENDED TO RELACE MEDICATIONS OR ELIMINATE THE ADVICE OF A COMPETENT HEALTH CARE PRACTITIONER.
      </p>
    </Grid>
  );
}

export default Disclaimer;
